### ISSUE TITLE
Spin configuration at different montecarlo steps

### ISSUE THREAD

**Issue by RomanPico** [nafiserb/ESpinS#5]
Dear Dr  Nafiseh Rezaei,

First of all, thanks for the code. It's very useful.

We're trying to obtaining the spin configuration (not the mean value) at different montecarlo steps in a given run (like taking pictures of different spin configurations at specified montecarlo steps).

We thought that this could be done by doing a suitable amount of warm up steps and then, doing only 1 montecarlo step obtaining one thermalized spin configuration from the file sconfig. Then by doing  N runs we get N thermalized spin configurations. Is this okay?

Alternatively, is it possible to obtain this information in a single montecarlo run? we guess that the program has this information in order to evaluate the energy in each montecarlo step, but it does not write it as far as we know.

Many thanks in advance.

**Comment by nafiserb** [comment]
Thank you for using the code. 
>We thought that this could be done by doing a suitable amount of warm up steps and then, doing only 1 montecarlo step obtaining one thermalized spin configuration from the file sconfig. Then by doing N runs we get N thermalized spin configurations. Is this okay?
**It is correct. But be careful, for each step, use the previous sconfig file.** 
>Alternatively, is it possible to obtain this information in a single montecarlo run? we guess that the program has this information in order to evaluate the energy in each montecarlo step, but it does not write it as far as we know.
**No, it is not possible. The sconfig file contains lots of information, so it takes a large hard disk space if we want to write this information for each step.**

**By the way, we recommend using the new update of code (Nov. 8) because there was an issue in the vispin program for spin visualization  (see issue #4)**
